### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'target_ids'

### ISSUE THREAD

**Issue by daiwk** [facebookresearch/generative-recommenders#1]
when I run `CUDA_VISIBLE_DEVICES=0 python3 train.py --gin_config_file=configs/ml-1m/hstu-sampled-softmax-n128-large-final.gin --master_port=12345` i got this error:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/opt/tiger/demo_codes/generative-recommenders/train.py", line 497, in mp_train_fn
    train_fn(rank, world_size, master_port)
  File "/home/tiger/.local/lib/python3.9/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/tiger/.local/lib/python3.9/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/tiger/.local/lib/python3.9/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/opt/tiger/demo_codes/generative-recommenders/train.py", line 334, in train_fn
    eval_dict = eval_metrics_v2_from_tensors(
TypeError: __call__() got an unexpected keyword argument 'target_ids'
  In call to configurable 'train_fn' (<function train_fn at 0x7f20346f44c0>)

**Comment by jiaqizhai** [comment]
Thanks for raising the issue. Could you clarify if you made any changes to the file locally?

eval_metrics_v2_from_tensors in data/eval.py should have the target_ids argument at head, and I just re-verified that script w/ the head commit locally (using python 3.8 and pt 2.0).

...
INFO:root:rank 0:  batch-stat (eval): iter 600 (epoch 12): NDCG@10 0.1662, HR@10 0.3125, HR@50 0.6328, MRR 0.1391 
INFO:root: rank: 0, batch-stat (train): step 600 (epoch 12 in 17.68s): 2.323231
INFO:root:rank 0: eval @ epoch 12 in 16.55s: NDCG@10 0.1520, NDCG@50 0.2126, HR@10 0.2778, HR@50 0.5518, MRR 0.1295

**Comment by daiwk** [comment]
when i use 
```
import inspect
print(inspect.signature(eval_metrics_v2_from_tensors))
```
i got output
```
(orig_func: ~F) -> ~F 
```
and i asked gpt, it says that means the decorator may not works..
and i see this function has the following decorator:
```
@torch.inference_mode
def eval_metrics_v2_from_tensors(
    eval_state: EvalState,
    model: NDPModule,
    seq_features: SequentialFeatures,
    target_ids: torch.Tensor,  # [B, 1]
    min_positive_rating: int = 4,
    target_ratings: Optional[torch.Tensor] = None,  # [B, 1]
    epoch: Optional[str] = None,
    include_full_matrices: bool = False,
    filter_invalid_ids: bool = True,
    user_max_batch_size: Optional[int] = None,
    dtype: Optional[torch.dtype] = None,
) -> Dict[str, List[float]]:
#...
```
so i upgrade my torch & fbgemm version :
```
pip3 install fbgemm-gpu==0.6.0
pip3 install torch==2.2.0
```
and now it works~i got the outputs:
```
INFO:root:rank 0: eval @ epoch 0 in 14.61s: NDCG@10 0.0193, NDCG@50 0.0402, HR@10 0.0425, HR@50 0.1404, MRR 0.0195
INFO:root:rank 0: eval @ epoch 1 in 14.34s: NDCG@10 0.0447, NDCG@50 0.0777, HR@10 0.0864, HR@50 0.2397, MRR 0.0422
```

**Comment by daiwk** [comment]
https://github.com/daiwk/generative-recommenders/commit/b14288e771adbb2322cfd40dfb676ae5e85735c6
maybe this commit will help
