### ISSUE TITLE
How to install hammer package used in triton_ragged_hstu_attention?

### ISSUE THREAD

**Issue by Lix1993** [facebookresearch/generative-recommenders#115]
https://github.com/facebookresearch/generative-recommenders/blob/6f218968188b23e3c7ea70aa71a5bc47dd673e7a/generative_recommenders/ops/triton/triton_ragged_hstu_attention.py#L30

**Comment by jiaqizhai** [comment]
Hi, that line should import the oss implementation on fallback (except ...). You may need to change 

    from hammer.oss.generative_recommenders.ops.triton.utils import (

to 

    from generative_recommenders.ops.triton.utils import (
