### ISSUE TITLE
question about the action part

### ISSUE THREAD

**Issue by levi77** [facebookresearch/generative-recommenders#12]
Hello, this is a great piece of work! However, the current public experimental results seem to be based on not incorporating action into the input. The author appears to have defined the input ( in the CombinedItemAndRatingInputFeaturesPreprocessor part )but there is no specific implementation part. Could you release code of this part?

**Comment by jiaqizhai** [comment]
Hi, thanks for your interest in our work! We do not currently use this class for the experiments in Section 4.1.1. In case we find a larger public dataset, we may add this back later.
