### ISSUE TITLE
question about RelativeBucketedTimeAndPositionBasedBias

### ISSUE THREAD

**Issue by ShuaiXuan** [facebookresearch/generative-recommenders#14]
when i see:
B = all_timestamps.size(0)
N = self._max_seq_len
t = F.pad(self._pos_w[:2 * N - 1], [0, N]).repeat(N)
t = t[..., :-N].reshape(1, N, 3 * N - 2)
r = (2 * N - 1) // 2

t=t[..., :-N] denotes [N,2 * N - 1]
how can it becomes (1, N, 3 * N - 2)

**Comment by jiaqizhai** [comment]
t = F.pad(..., [0, N]).repeat(N) changes the shape of t.
