### ISSUE TITLE
token的组织形式

### ISSUE THREAD

**Issue by llmmodel123** [facebookresearch/generative-recommenders#19]
<img width="1015" alt="image" src="https://github.com/facebookresearch/generative-recommenders/assets/170526427/86d1a9c7-0cd5-47f4-b627-e949afe8520f">
https://github.com/facebookresearch/generative-recommenders/blob/main/data/dataset.py#L142 你好，我看代码这里的每个item代表一个token，但是我看论文里说是item0，action0，item1，action1这种形式来作为输入的格式的，不知道我是哪里理解有问题？

**Comment by jiaqizhai** [comment]
Hi,

The current open sourced code is only intended for reproducing the experiments in 4.1.1 (public datasets) / 4.2 (efficiency). Our setting in 4.1.1 followed traditional sequential recommender setups like GRU4Rec, SASRec, etc. which do not use the interleaved setting (4.1.2). We'll see how to make 4.1.2. etc easier to reproduce later.
