### ISSUE TITLE
Stochastic Length

### ISSUE THREAD

**Issue by djx2726889** [facebookresearch/generative-recommenders#2]
Great Work! However, there doesn't appear to be any implement of the Stochastic Length and Sampling Technique Γ(S, L) in the paper.

**Comment by jiaqizhai** [comment]
Hi - part of the challenge here is that we do not yet have publicly available large-scale datasets with long sequence lengths, therefore we only ran SL on our internal dataset. The current repo is intended for reproducing public experiments so far.

In case you have suggestions on datasets to use -- ideally with several thousands of (user, item) interactions on average -- we would love to help make related implementations available!
