### ISSUE TITLE
Triton code

### ISSUE THREAD

**Issue by wookjeHan** [facebookresearch/generative-recommenders#27]
Hi,

Thanks for sharing this fascinating work!
I noticed that there are some Triton classes and functions defined in `ops/triton/triton_ragged_hstu_attention.py`. However, it seems that the current HSTU implementation primarily uses Torch and FBGEMM rather than Triton.

Could you please clarify where these Triton classes and functions are utilized?

Thank you!

**Comment by jiaqizhai** [comment]
Hi,

We plan to integrate the two in the open source code but it's not done yet. Please expect updates in upcoming weeks.
