### ISSUE TITLE
The detail about the generation of tokens?

### ISSUE THREAD

**Issue by glb400** [facebookresearch/generative-recommenders#28]
Hello, guys. Thanks for the great work – it's been super helpful.

I'm trying to replicate this method you've shared. Actually, I'm curious about how you generate tokens based on corresponding item features? 

More specifically, how you deal with the side information of item (e.g., cate/brand)? I'd love to know that whether you treat sideinfo as extra tokens (e.g., <item_id><cate_id><brand_id>), or input all features of the item into MLP and take its output as a token, or some method else?

Really appreciate your help on this!

**Comment by jiaqizhai** [comment]
Hi, the most straightforward way to encode category information and brand information would be to use them (together with id information) to derive the content token representation $\Phi_i$s. An MLP should work as an initial baseline?

**Comment by glb400** [comment]
Thanks for your response. 

In light of that, I'm curious about what side information you have utilized to derive the content token representation? 

Additionally, do you derive this representation by simply concatenate item id & sideinfo together in practice? Or use an MLP after concatenation?

Looking forward to your reply!

**Comment by glb400** [comment]
> Hi, the most straightforward way to encode category information and brand information would be to use them (together with id information) to derive the content token representation $\Phi_i$s. An MLP should work as an initial baseline?

Thanks for your response. 

In light of that, I'm curious about what side information you have utilized to derive the content token representation? 

Additionally, do you derive this representation by simply concatenate item id & sideinfo together in practice? Or use an MLP after concatenation?

Looking forward to your reply!

**Comment by jiaqizhai** [comment]
Hi - we cannot disclose the specific features we used in our internal settings, but GRs used a strict subset of features used by our DLRM baselines. We'll think about how to make this particular aspect easier to test.
