### ISSUE TITLE
 Stochastic Length strategy may cause user history features inconsistent online and offline 

### ISSUE THREAD

**Issue by muGithub** [facebookresearch/generative-recommenders#31]
How to solve the problem of inconsistent online and offline user history features that may be caused by random sampling(stochastic length)

**Comment by jiaqizhai** [comment]
Hi - we can think about Stochastic Length as a way to train on short sequences and infer on long sequences. So the problem setting is similar to NTK-Aware RoPE and NTK-by-parts etc. that we discussed in Section F, except Stochastic Length is designed to enable length extrapolation on recommendation sequences with extremely high cardinality features.

**Comment by muGithub** [comment]
It's a confirmed letter, I have received your letter, thank you!  addressor: Guo, Youtian
