### ISSUE TITLE
triton flash attention with bias  backward.

### ISSUE THREAD

**Issue by NAP-GHJ** [facebookresearch/generative-recommenders#33]
When will the triton version of flash attention with bias backward be released?  We are all looking forward to it.

**Comment by jiaqizhai** [comment]
This is on our radar but may take additional time. In case people are interested in this from a performance optimization perspective, please reach out to us offline.

**Comment by NAP-GHJ** [comment]
> This is on our radar but may take additional time. In case people are interested in having this sooner from a QPS/performance optimization perspective, please reach out to us offline.

How can I contact you? My email address is 18052095653@189.cn

**Comment by haojiwei** [comment]
> This is on our radar but may take additional time. In case people are interested in having this sooner from a QPS/performance optimization perspective, please reach out to us offline.

I'm interested in performance optimization. Could you send me a copy? My email is qishiqihao@gmail.com

**Comment by zzq96** [comment]
> This is on our radar but may take additional time. In case people are interested in having this sooner from a QPS/performance optimization perspective, please reach out to us offline.

Hi, I'm interested in performance optimization of triton fused attention.  How can I contact you? my email is aa1402806685@gmail.com

**Comment by wookjeHan** [comment]
Hi I am also interested in! Could you please contact me via wookje.han@columbia.edu?

**Comment by matfu-pixel** [comment]
Hi, I'm interested in performance optimization too. Could you send me a copy? artmatman50@gmail.com

**Comment by gmlyytt-YANG** [comment]
Hi, I'm interested in performance optimization of triton fused attention. How can I contact you? my email is [gmlytt@outlook.com](mailto:gmlytt@outlook.com)

**Comment by maidousi** [comment]
Hi, I'm interested in performance optimization too and is working hard on improving performance. Could you send me a copy? Thanks! my email is haoripei@gmail.com

**Comment by jiaqizhai** [comment]
To clarify, if you are already working with Meta teams under NDA, please feel free to reach out to them directly. We do not share code over emails. Otherwise we are also investigating ways to make reproducing related experiments easier and will update this github repo when there are updates.
