### ISSUE TITLE
Regarding padding, gr_output_length

### ISSUE THREAD

**Issue by wookjeHan** [facebookresearch/generative-recommenders#36]
Dear team,

First of all thanks for providing super interesting projects!

Based on my current understanding, the shape of the result from the forward pass is (Batch Size, Seq_Len, Embedding) and `result[:, i, :]` is used to predict the (i+1)-th token.

If this is correct, why do we set `padding_length` as `max_sequence_length+1` and append at least one padding token after each sequence [reco_dataset.py](https://github.com/facebookresearch/generative-recommenders/blob/main/data/reco_dataset.py#L53)?

Can we simply predict the target token with setting `padding_length` as `max_sequence_length`??

I am also wondering what `gr_output_length` means and why `gr_output_length` is larger than one.
Isn't this model predicting one token at once?

**Comment by jiaqizhai** [comment]
Hi, the exact rab_{p, t}(i, j) setting in this particular codebase is based on relative timespan between timestamp[i] and timestamp[j+1] (not timestamp[j]), so we need to pad sequence length by 1.
