### ISSUE TITLE
Are we using oldest rating as target?

### ISSUE THREAD

**Issue by yundai424** [facebookresearch/generative-recommenders#42]
Hi team, thanks for the super innovative and solid paper! I have a naive question about the data prep part -- it's highly possible that i'm just missing off some piece of code. Assuming the preprocessed MovieLens data is sorted by unixtimestamp in ascending order (as by looking at `sasrec_format.csv` file), [here](https://github.com/facebookresearch/generative-recommenders/blob/main/data/dataset.py#L117) we're taking the oldest rating as the target, and this is quite confusing to me. Combining the following code piece
```
if self._chronological:
            historical_ids.reverse()
            historical_ratings.reverse()
            historical_timestamps.reverse()
```
it looks like we're expecting the rating per user in the preprocessed dataset to be ordered in descending order by timestamp instead? 🤔

**Comment by jiaqizhai** [comment]
Thanks for your interest in our work! iirc, the default order (after preprocessing) is reverse chronological. We reversed the order to chronological because of decoding related use cases (briefly discussed in the paper, but they are not yet implemented in this version).

**Comment by yundai424** [comment]
@jiaqizhai thanks a lot for the clarification! Could it be a typo that we missed `ascending=False` [here](https://github.com/facebookresearch/generative-recommenders/blob/main/data/preprocessor.py#L233) or it could be i'm missing some code somewhere

**Comment by yundai424** [comment]
@jiaqizhai thanks a lot for the explanation! Turns out I missed out [this](https://github.com/facebookresearch/generative-recommenders/blob/main/data/dataset.py#L79) line 😄 now everything makes sense! I'll go ahead close this issue.
