### ISSUE TITLE
adding bias bwd makes fused attention bwd  30x slower, any suggestions?

### ISSUE THREAD

**Issue by zzq96** [facebookresearch/generative-recommenders#43]
I have written a bwd triton code , but I found that after adding the bias bwd , the speed is 30 times slower.
The following is the time_weight bwd code I wrote:
```python
def fused_attention_bwd():
    // use to reduce atomic_add 
    acc_d_tw = tl.zeros([BUCKET_NUM + 1])  # time_weight grad in shm
    for start_m in range(low, high, BLOCK_M): 
        d_qk = ... # grad of qk, [BLOCK_M,BLOCK_N]
        if USE_TIME_BIAS:
            bucket_offset = tl.arange(0, BUCKET_NUM + 1) 
            ts_mask = ts[None, :, :] == bucket_offset[:, None, None]  # [num_buckets+1, B_M, B_N]
            ts_d = tl.where(ts_mask, d_qk[None, :, :], 0) #[num_buckets+1, B_M, B_N]
            d_sum = tl.sum(ts_d, axis=1) #[num_buckets+1, B_N]
            d_sum = tl.sum(d_sum, axis=1) #[num_buckets+1]

            acc_d_tw += d_sum #[num_buckets+1]

    tl.atomic_add(acc_d_tw)  # add to global  time_weight grad
```
any suggestions?

**Comment by jiaqizhai** [comment]
Hi, 

Missed this thread earlier. Excessive use of atomic_add can indeed slow down bwd. We plan to release reference bwd implementation in the future. We've also held the 2nd Triton developer conference (https://tritondeveloperconference.splashthat.com/) earlier this week, where you can find some tips to optimize Triton code.

Hope this helps!
