### ISSUE TITLE
is rating not used?

### ISSUE THREAD

**Issue by yueming-zhang** [facebookresearch/generative-recommenders#45]
Thank you for the great work!

Looks below classes are not used in training and inference: 
- LearnablePositionalEmbeddingRatedInputFeaturesPreprocessor
- CombinedItemAndRatingInputFeaturesPreprocessor

This means we don't use rating as feature. Is my understanding correct? Do you expect include rating as features make any difference on Movielens?

**Comment by jiaqizhai** [comment]
Hi - Section 4.1.1's setting (the primary focus of this codebase) does not use rating for consistency with prior work. We will likely add an alternative setting that use rating later. In case people have time please feel free to open PR too :)
