### ISSUE TITLE
user-item interaction question

### ISSUE THREAD

**Issue by a6802739** [facebookresearch/generative-recommenders#5]
hi, guys, I have a question about user-item interaction here.

I want to test HSTU in our application, we have a lot of user-item impression, click and buy action. I want to construct the sequence with these action. If I just simple construct the sequence  with the order of action timestamp, because for same user-time pair, we have more than one impression action, we'll have many same user-item-impression with different timestamp within one user sequence in one day.

I want to ask for the situation above, whether we need to deduplicate the  impression action? Whether we should guarantee one user-item impression with the latest timestamp in one day.

**Comment by jiaqizhai** [comment]
Hi - I assume you mean that the user comes back to purchase the item after viewing that item a few hours ago? I'd recommend grouping these into two events given the two events happened sufficiently far apart.
