### ISSUE TITLE
Items and actions setting.

### ISSUE THREAD

**Issue by juanelenter** [facebookresearch/generative-recommenders#54]
Can the authors provide a version that uses both items and actions in the historical sequence? Or a guide on how to adapt the code to handle this case using the LearnablePositionalEmbeddingInputFeaturesPreprocessor or CombinedItemAndRatingInputFeaturesPreprocessor classes ?

**Comment by jiaqizhai** [comment]
Hi - we do not have this part implemented for public dataset (given the need to align with prior baselines for HSTU evals), only for internal datasets. But I agree that it's very valuable to have one version for reference purposes. We'll try to get to this soon.
