### ISSUE TITLE
 Confused About  RelativeBucketedTimeAndPositionBasedBias

### ISSUE THREAD

**Issue by yuanyifang** [facebookresearch/generative-recommenders#55]
Hi, had anyone ever confused about RelativeBucketedTimeAndPositionBasedBias function. 
I used some test code to check the results of 
`ext_timestamps[:, 1:].unsqueeze(2) - ext_timestamps[:, :-1].unsqueeze(1)' ,
 and found that the first elements of the data is not zero. 
I think this is the timediff results, the same elements shoud be zero, and the first elements shoud be the first action time - the first action time. but the code shows the result is the second action time - the first action time  
But I don't know why
```
ext_timestamps = torch.cat([all_timestamps, all_timestamps[:, N-1:N]], dim=1)
# ext_timestamps[:, 1:].unsqueeze(2) - ext_timestamps[:, :-1].unsqueeze(1)
bucketed_timestamps = torch.clamp(
    self._bucketization_fn(ext_timestamps[:, 1:].unsqueeze(2) - ext_timestamps[:, :-1].unsqueeze(1)),
    min=0,
    max=self._num_buckets,
).detach()
```

**Comment by jiaqizhai** [comment]
Hi - the specific implementation we used here computes delta of timestamp[j+1] and timestamp[i] for the traditional next-token prediction setting (as we need to predict the item at j+1 for public datasets). This is why you see "ext_timestamps[:, 1:].unsqueeze(2) - ext_timestamps[:, :-1].unsqueeze(1)" (1: and :-1 are intended) in the code. We will add other variants later.
