### ISSUE TITLE
Triton is running too slow?

### ISSUE THREAD

**Issue by bzxc** [facebookresearch/generative-recommenders#56]
Compared to the same structure(the qkv attention) I implemented with TensorFlow, triton runs 10 to 20 times slower. With the help of nsight system, I found that cudaMemcpySync takes off much time while triton is executing. Would you happen to have any ideas about that?

I feed data like this,
batch: 8
seq_len: 8192, where each seq_len are the same size.
emb_size = attn_size = linear_size
As I changed the data size by a multiplier of 2

On Nvidia A30

**Comment by bzxc** [comment]
emb_size = attn_size = linear_size = 128, sry for the omission

**Comment by jiaqizhai** [comment]
It's hard for us to debug without more information. But we are hosting the 2nd Triton developer conference at Fremont, CA on 09/17 (RSVP: https://tritondeveloperconference.splashthat.com/). Join us to learn about how to write highly efficient accelerator code :)
