### ISSUE TITLE
Having issues of running the code 

### ISSUE THREAD

**Issue by hamid-maei** [facebookresearch/generative-recommenders#58]
I have followed the instructions but am having trouble running the code using the provided script. Additionally, I am experiencing issues installing Apex, and I'm not sure if these issues are related. Has anyone successfully run the code on a fresh Ubuntu machine? I am using an A100 machine with fairly large memory, so compatibility should not be an issue. I have also installed CUDA and official pytorch.

**Comment by jiaqizhai** [comment]
Hi, people have previously tested this code with CUDA 11.6/12.1 etc. based on instructions outlined in README.md. If you have a specific issue you are running into, please let us know the exact errors you encountered?
