### ISSUE TITLE
examples for merging auxiliary time series

### ISSUE THREAD

**Issue by foreverYoungGitHub** [facebookresearch/generative-recommenders#59]
Thank you for your great work!

In the paper, it states:

> "The remaining features are generally time series that slowly change over time, such as demographics or followed creators. We compress these time series by keeping the earliest entry per consecutive segment and then merge the results into the main time series."

It appears that this method is not currently demonstrated in the public dataset. Could the authors provide examples that utilize both the main time series and auxiliary time series? Alternatively, a guide with pseudocode on how to adapt this approach would be greatly appreciated.

Additionally, is there a more detailed evaluation conducted with or without the auxiliary time series? Specifically, is it GR (interactions only) vs. GR in Tables 6 and 7?

**Comment by jiaqizhai** [comment]
Hi, the current public datasets we are using don't really have these features. $G_i$s and $F_i$s in Figure 2 in the paper should be a good reference.
