### ISSUE TITLE
about forward of `triton_ragged_attention_relative_bias` and `triton_ragged_attention`

### ISSUE THREAD

**Issue by a6802739** [facebookresearch/generative-recommenders#60]
Hi, guys. I saw the forward implementation of `triton_ragged_attention_relative_bias` and `triton_ragged_attention`, but I didn't see the backward implementation. For now, could I use `triton_ragged_attention_relative_bias` and `triton_ragged_attention` within model structure?

**Comment by jiaqizhai** [comment]
Hi, these functions should be compatible with model file. It's on our radar to add glue code to hook up these two together (alongside with bwd implementation etc), but if it's urgent please feel free to glue together code yourself.
