### ISSUE TITLE
Evaluation result is lower than reported in paper

### ISSUE THREAD

**Issue by yjdy** [facebookresearch/generative-recommenders#61]
Dear author,
Thanks for the great work. I trained hstu and sasrec with your code on ml-1m, but the results of last epoch are significantly lower than the result you reported.

Do the reported results are the best evaluation result during training? If so, how do you select the best result.

Best regards

**Comment by jiaqizhai** [comment]
Hi, please apply early stopping on validation set to determine which epoch to use for reading (and please check https://github.com/facebookresearch/generative-recommenders/issues/8 for more details re code used here).
