### ISSUE TITLE
fbgemm-gpu version?

### ISSUE THREAD

**Issue by jq** [facebookresearch/generative-recommenders#62]
I run the code inside `docker nvcr.io/nvidia/pytorch:24.07-py3`
with `docker run --gpus all -it -v $(pwd):/workspace/torch nvcr.io/nvidia/pytorch:24.07-py3`
and install by `pip3 install gin-config absl-py scikit-learn scipy matplotlib numpy apex hypothesis pandas fbgemm_gpu iopath`
the fbgemm-gpu is 0.8.0  then I run `CUDA_VISIBLE_DEVICES=0 python3 train.py --gin_config_file=configs/ml-1m/hstu-sampled-softmax-n128-large-final.gin --master_port=12345`
and it has error
```
/usr/local/lib/python3.10/dist-packages/fbgemm_gpu/experimental/gen_ai/fbgemm_gpu_experimental_gen_ai_py.so: undefined symbol: _ZN4c10d23ncclGetErrorWithVersionE12ncclResult_t
```
then I change it to fbgemm-gpu==0.6.0  get new error:
`AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'`

I switch to `docker nvcr.io/nvidia/pytorch:24.01-py3`
which has the torch 2.2.0, get the same error?
what fbgemm lib version should I use?

Thanks a lot!

**Comment by jiaqizhai** [comment]
0.6.0, please refer to https://github.com/facebookresearch/generative-recommenders/issues/35

We may need some minor updates for 0.8.0 (please feel free to open PRs)
