### ISSUE TITLE
HSTU output will always padded to max_sequence_length

### ISSUE THREAD

**Issue by newsbreakDuadua9** [facebookresearch/generative-recommenders#63]
When I apply the code on my own dataset, I found the encoder returned by:
get_sequential_encoder

**Will always pad its output to max_sequence_length + gr_output_length, which is passed by:**
    model = get_sequential_encoder(
        module_type=main_module,
        max_sequence_length=dataset.max_sequence_length,
        max_output_length=gr_output_length + 1,
        embedding_module=embedding_module,
        interaction_module=interaction_module,
        input_preproc_module=input_preproc_module,
        output_postproc_module=output_postproc_module,
        verbose=True,
    )
    
 **Why we do that?**
 and I also found it's confusing that we check:
 **assert output_embeddings.size() == supervision_embeddings.size()**
in:
https://github.com/facebookresearch/generative-recommenders/blob/main/modeling/sequential/autoregressive_losses.py
**Which is always true for a transformer.**

**Is it a bug? That the forward code in HSTU encoder always pad its output to max length? Why we cant let it pad to max length in batch?**

**Right now, I figured out a quick fix for it that let:**

seq_embeddings = model_engine(
                past_lengths=seq_features.past_lengths,
                past_ids=seq_features.past_ids,
                past_embeddings=input_embeddings,
                past_payloads=seq_features.past_payloads,
)  # [B, X]
# fix 
seq_embeddings = seq_embeddings[:, :input_embeddings.size()[1], :]
To remove the 0 padding

Thank You!
Really need the help!

**Comment by jiaqizhai** [comment]
Hi,

a) You are definitely right that padding to max length in a batch is more efficient, and is what we actually do for efficiency-related experiments. The associated code have not been fully updated to use new kernels.

b) the asserts are added for early debug purposes, please feel free to remove them.
