### ISSUE TITLE
How to achieve consistency between offline training and online prediction when exposing multiple items at a time?

### ISSUE THREAD

**Issue by frankenstein-kk** [facebookresearch/generative-recommenders#67]
How to achieve consistency between offline training and online prediction when exposing multiple items at a time?
eg：item1, action1, item2, action2, item3, action3, item4, action4, item5, action5 ...
Items 2-4 belong to the same exposure, when training item4, item2 and item3 are involved in ATTENTION calculation?

**Comment by jiaqizhai** [comment]
Hi, you can likely modify the M-FALCON algorithm (page 25-26 https://arxiv.org/pdf/2402.17152v3) and use that setup for training in this case?
