### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by cb521** [facebookresearch/generative-recommenders#7]
Hi team, which continer are you using ? I tried the "nvcr.io/nvidia/pytorch:23.11-py3" continer, but there has always been an issue with "RuntimeError: No such operator fbgem:: jagged_2d_to_dense"

**Comment by cb521** [comment]
I also noticed that you "import fbgemm_gpu", but never use this package for now, so why import this ?

**Comment by jiaqizhai** [comment]
Please follow the instructions in README.md. Installing fbgemm_gpu 0.6.0 (or using some container with this dependency) should work. It's used in hstu.py.

**Comment by SAI990323** [comment]
> Please follow the instructions in README.md. Installing fbgemm_gpu 0.6.0 (or using some container with this dependency) should work. It's used in hstu.py.

I am using python 3.10.10, pytorch 2.0.0, fbgemm_gpu 0.6.0, but I also met this error, are there any other possible solutions?
