### ISSUE TITLE
What computing power configuration is required?

### ISSUE THREAD

**Issue by fyx18** [facebookresearch/generative-recommenders#70]
What computing power configuration is required for trainging the GRs? With the experiment setup in the article, i.e. 256 H100, how long should the model be trained?

**Comment by jiaqizhai** [comment]
Hi,

Thanks for your interest in our work. While we cannot disclose the exact training setup used in production, you should be able to infer some coarse characteristics based on Figure 1, Figure 7, etc.

Both test and control in 4.1.2 and 4.2 / 4.3 are trained on the same amount of data, and the amount of data is determined based on what our recommendation teams typically use for production ranking/retrieval models' offline iterations. 

Hope this helps!
