### ISSUE TITLE
Is there some guides to run GR in model parallel?

### ISSUE THREAD

**Issue by jimmycao** [facebookresearch/generative-recommenders#74]
Hi, guys, thanks for your great work!

could you please drop me a guide for training GR in a distributed GPU cluster with model parallel? not just data parallel. Since detailed in your paper, 64-256 H100 are allocated to run GR.  

Someone told me that Megatron or Deepspeed might be needed and the model script should be modified to adapt.  

As a newbie, I really need your advice.  many thanks.

**Comment by jiaqizhai** [comment]
Hi,

Thanks for your interest in our work. The training code we open sourced is intended for public datasets only. Deepspeed / FSDP / Megatron etc are indeed possible frameworks to try if you want model parallelism training on your internal large datasets.
