### ISSUE TITLE
Possible discover a dataset bug.

### ISSUE THREAD

**Issue by cb521** [facebookresearch/generative-recommenders#8]
Hi team, Is there a problem with this piece of code in dataset processing?

https://github.com/facebookresearch/generative-recommenders/blob/ba50546114fa088cc828e8a4321e31ef49a4440b/data/reco_dataset.py#L45 And https://github.com/facebookresearch/generative-recommenders/blob/ba50546114fa088cc828e8a4321e31ef49a4440b/data/reco_dataset.py#L52

I think it should read the "sasrec_format_by_user_train.csv"  and "sasrec_format_by_user_test.csv" ?

**Comment by jiaqizhai** [comment]
The standard split on MovieLens for sequential models is by relative positions in the sequence. This is implemented by ignore_last_n in the data loader (eg 0 = test, 1 = validation, 2=train). 

by_user split is something we implemented for a different use case, but is not currently using. We'll clean up that code a bit later.
