### ISSUE TITLE
ItemFeatures not used in training

### ISSUE THREAD

**Issue by rubydevelop** [facebookresearch/generative-recommenders#85]
I was reading through the code and realized that the actual item features such as age, gender, sex, occupation etc. for users and genre, year, title for movies is not used since `ItemFeatures` is not passed back in the `reco_dataset`.  Could you explain why you omitted it from training or am I not tracing its usage properly?

**Comment by jiaqizhai** [comment]
The current codebase is primarily intended for comparing results on public datasets. We hence only use item ID features for consistency with baseline implementations in the traditional sequential recommender setting (ref GRU4Rec, SASRec, MoL, etc.). You can add other features if you run this in large-scale production settings, which we discussed ways to do so in our paper.
