### ISSUE TITLE
perhaps remove item_feature_embedding_dim in gin config for amzn-books?

### ISSUE THREAD

**Issue by zhuochenKIDD** [facebookresearch/generative-recommenders#9]
ValueError: Configurable 'train_fn' doesn't have a parameter named 'item_feature_embedding_dim'.
  In file "configs/amzn-books/sasrec-sampled-softmax-n512-final.gin", line 14
    train_fn.item_feature_embedding_dim = 0

**Comment by jiaqizhai** [comment]
Good catch! Should be addressed by https://github.com/facebookresearch/generative-recommenders/pull/10
