### ISSUE TITLE
Integration with TorchRec

### ISSUE THREAD

**Issue by sbhavani** [facebookresearch/generative-recommenders#91]
Are there any plans to integrate the embedding_modules or custom samplers back into TorchRec?

**Comment by jiaqizhai** [comment]
Hi, it should be easy to implement an EmbeddingModule (currently in https://github.com/facebookresearch/generative-recommenders/blob/main/generative_recommenders/modeling/sequential/embedding_modules.py) with EmbeddingCollections from TorchRec. Note you likely want to swap out trainer code as TorchRec uses DMP etc. if you go with this route, so we do not have an official ETA yet, but it should be easy to do so in your own codebase if you use torchrec.
