### ISSUE TITLE
How to deal with unknown tokens in practice?

### ISSUE THREAD

**Issue by isofun** [facebookresearch/generative-recommenders#95]
Hello, it's a great work! I have some problem about the unknown token(newly created items). Because of the long sequence, only user side category features can be merged into the main time series. If a new item comes, the GR model has no information about it, and the ranking score should be very small, and finally this new item will never be exposed to users. Did I made some mistake in the above opinion? And how to deal with the totally unknown item, what kind of auxiliary feature should I take, or just use some forced expose re-rank strategy? Looking forward to your reply.

**Comment by jiaqizhai** [comment]
Thanks for your interest in our work and for the compliments! 

We can in fact incorporate item-side features besides item id in the GR formulation without increasing sequence length. There are related discussions in https://github.com/facebookresearch/generative-recommenders/issues/28.

**Comment by isofun** [comment]
> Thanks for your interest in our work and for the compliments!
> 
> We can in fact incorporate item-side features besides item id in the GR formulation without increasing sequence length. There are related discussions in #28.

That helps, thank you!
